services:
  PostgreSQL:
    image: postgres:16
    container_name: aston_postgres
    environment:
      POSTGRES_DB: ${ASTON_POSTGRES_DB}
      POSTGRES_USER: ${ASTON_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ASTON_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ASTON_POSTGRES_USER} -d ${ASTON_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: aston_pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ASTON_PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ASTON_PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge